USE [yamaharota]
GO

SET XACT_ABORT ON
GO

BEGIN TRANSACTION
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'Rota')
BEGIN
	CREATE TABLE Rota (
    Id int IDENTITY (1,1) NOT NULL,	
    Origem char(3) NOT NULL, 		 
    Destino char(3) NOT NULL,  
    Valor decimal (15, 4) NOT NULL
);
END
GO

COMMIT TRANSACTION
GO
